### ISSUE TITLE
Refactor: Card 

### ISSUE THREAD

**Issue by otterp012** [otterp012/otter-log#23]
## description
`Card` 컴포넌트를 리팩토링합니다. 현재의 카드 컴포넌트는 다음과 같은 문제를 가지고 있습니다.
```tsx
// vertical Card와, Card 컴포넌트를 동시에 사용할 수 있다고 생각하여 진행했던 코드
const Card: React.FC<Props> = ({
...
}) => {
  const style = CardStyles[cardType];
  const isVerticalCard = cardType === "verticalCard";
  // 외부에서 주입한 style 객체로부터, 해당 card의 css를 받아와서 작동됩니다.
```
원래의 의도는 `Card` 컴포넌트를 재사용하는 부분이었지만, 의도와 달리 `css` 와 더욱 깊게 연결되어 재사용이 불가능한 컴포넌트가 되었다는 생각이 들었습니다.

- `vetical Card` 컴포넌트를 다른 컴포넌트로 따로 작성하는 방법도 도움이 될 것이고 또는 `Card` 컴포넌트를 조금 더 작은 단위로 쪼개어 두는 방법도 도움이 될 수 있을 것 같습니다.

## TO-DO
- [ ] `Card` 컴포넌트 리팩토링
- [ ]  `Featured` 컴포넌트 작성
- [ ] 모바일뷰 작동 여부 확인
